version: '2'

# networks:
#   app-tier:
#     driver: bridge

services:
  etcd:
    image: 'bitnami/etcd:latest'
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
    ports:
      - 2379:2379
      - 2380:2380
    # networks:
    #   - app-tier

  api:
    build: api/
    ports:
      - 5000:5000
    environment:
      ETCD_HOST: etcd
      ETCD_PORT: 2379
    volumes:
      - ./api/src:/app
    command: 
      - --reload
  
  controller:
    build: controller/
    environment:
      ETCD_HOST: etcd
      ETCD_PORT: 2379
    volumes:
      - ./controller/src:/app
  
    # networks:
    #   - app-tier


